language: scala
scala:
  - 2.10.3
jdk: oraclejdk7
env:
  - PLAY_VERSION=2.2.6
before_script:
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  email:
    - sahebmotiani@gmail.com